version: '3.8'
services:
  postgresql_db:
    image: postgis/postgis:11-3.3-alpine
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker" 
      POSTGRES_DB: "aoi_app"
    ports:
      - "5432:5432"
    volumes: 
      # copy the sql script to create tables
      - ./data/pgsql:/var/lib/postgresql/data
      - ./server/db.sql:/docker-entrypoint-initdb.d/create_tables.sql
      
  backend:
    container_name: backend
    build:
      context: server
      dockerfile: Dockerfile # Dockerfile in server folder
    ports:
      - 3005:3005
    depends_on:
      - postgresql_db
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: client
      dockerfile: Dockerfile # Dockerfile in client folder
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: always